spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user-service
    username: root
    password: CroKusPRreP9KqOFV1sG
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
